### ISSUE TITLE
Misleading wording in ansible_network.pdf slide deck

### ISSUE THREAD

**Issue by colin-mccarthy** [network-automation/linklight#174]
##### SUMMARY
In the ansible_network.pdf slide deck there is a slide on modules and one of the bullet points says... 

* modules are idempotent 

I don't consider them idempotent and we may be misleading folks who come to the workshops.

##### ISSUE TYPE
 - Bug Report

**Comment by colin-mccarthy** [comment]
I've had issues on engagements where the ios_config module didn't work impotently, the customer was upset because they are taught from day one that all modules are idempotent. Maybe we can adjust this to set a clearer expectation on how the network modules work.

**Comment by abenokraitis** [comment]
Proposed change:
s/are idempotent/can be idempotent

**Comment by colin-mccarthy** [comment]
I wonder if we could have a slide that explains how for example the iOS_config module works and explains that it does a show run command and checks against that before pushing the command. Also, how do you submit a PR on these PDFs?

**Comment by IPvSean** [comment]
> Also, how do you submit a PR on these PDFs?

@colin-mccarthy the short answer is the slides were purposely put into Google slides based on SA feedback which makes them more difficult to get PRs and treat them as code.  There is google slide link on the readme https://github.com/network-automation/linklight/blob/master/decks/README.md, you can "make a copy" and make a slide and ping me internally since you are a red hat employee.  The best use of time for slide work would be to attend the weekly linklight sync we have internally with the SA commerical team (alongside @jmcleroy , @willtome and Ford).  This month is not the best with SKO and people taking PTO but we can sync up soon.  I think we have not synced up b/c you were on paternity leave and I was on PTO.

In the mean time I think what @abenokraitis  mentioned will be sufficient.  They can be idempotent, this is something if you attended a workshop with me, that I speak to, and should update this more clearly in the speaker notes.  The fact is that customer want the concept of idempotent so we should talk to it at a high level, a more correct term might be stateful automation.

The concept of idempotency is covered in the lab exercise that @termlen0 helped put together.  I agree we need some new slides updates, I am working with the SA teams for some overhauls soon.

**Comment by colin-mccarthy** [comment]
Sounds good, I think what @abenokraitis mentioned is a good start. 

I will try and attend the Linklight sync and pitch a new slide explaining how the iOS_config module works. I think that is valuable knowledge for someone attending a workshop. I also speak to it when I present but would like to see a slide on it in the future.
