### ISSUE TITLE
Issues with ssh key handling

### ISSUE THREAD

**Issue by kyleabenson** [network-automation/linklight#3]
If I try to use the provisioner with this option commented out:
ec2_key_name:

The provisioner pauses while trying to trust the newly created ssh key

If I use an existing key, such as one I've imported into AWS, the teardown destroys that key. Assuming I have an existing key, I probably don't want that key removed from AWS during teardown, right?

**Comment by IPvSean** [comment]
>The provisioner pauses while trying to trust the newly created ssh key

Do you know which task you were on?

**Comment by IPvSean** [comment]
@gdykeman @kyleabenson @jmcleroy 

I think I see the issue finally that is happening on some installs.  The ssh-add seems to be a bad way to create and add a SSH key on the fly.  After reading through http://rabexc.org/posts/pitfalls-of-ssh-agents I realized the the ssh-add might work on certain distributions, but not all.  I think RHEL/CENTOS 7.5 doesn't start ssh agents by default... but we also don't want to make the playbook so specific to RHEL that it won't work on MacOS (or wahtever else)

So what I did is just deprecated the requirement for ssh-add.  If the host operating system DOES have ssh-agent running it will use ssh-add, otherwise it use lineinfile to add an identifyfile like this->

```
[sean@centos provisioner]$ cat ~/.ssh/config
Host *
     User ec2-user
     IdentityFile /home/ec2-user/.ssh/aws-private.pem
```

That way it will use the file, rather than relying on ssh-add.  This SEEMS to work.  Can one of you try this from Engine?  After we get it working on Engine I can try tower.
